---
# tasks file for rdo-repos
- block:
  - name: Find fedora repos
    find:
      paths: /etc/yum.repos.d/
      patterns: 'fedora*.repo'
    register: fedora_repo_files

  - name: Remove base fedora repos
    file: path={{ item.path }} state=absent
    with_items: "{{ fedora_repo_files.files }}"
    become: true

- name: Install delorean-deps repo
  get_url:
    url: https://trunk.rdoproject.org/fedora/delorean-deps.repo
    dest: /etc/yum.repos.d/delorean-deps.repo
  become: true

- name: Install delorean repo
  get_url:
    url: https://trunk.rdoproject.org/fedora/{{ rdo_fedora_repo }}/delorean.repo
    dest: /etc/yum.repos.d/delorean.repo
  become: true

