---
- name: reboot server
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  become: true
  ignore_errors: true

# wait 15 seconds for the reboot to happen as we can get a race condition
# if ssh is still answer when we go looking for it
- pause:
    seconds: 15

- name: wait for server to start
  local_action: wait_for host={{ ansible_host }} search_regex=OpenSSH port=22 timeout=300 delay=10
  become: false
